apiVersion: v1
kind: Secret
metadata:
  name: splitsmart-secrets
type: Opaque
stringData:
  DB_USER: CHANGEME
  DB_PASSWORD: CHANGEME
  DB_NAME: CHANGEME
  JWT_SECRET: CHANGEME
  GOOGLE_CLIENT_ID: CHANGEME
  GOOGLE_CLIENT_SECRET: CHANGEME
  GOOGLE_CALLBACK_URL: CHANGEME
  GROQ_API_KEY: CHANGEME
  CLIENT_URL: CHANGEME