apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: server
          image: splitsmart-server:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
          env:
            - name: PORT
              value: "5000"
            - name: DB_HOST
              value: postgres
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: splitsmart-secrets
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: splitsmart-secrets
                  key: DB_PASSWORD
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: splitsmart-secrets
                  key: DB_NAME
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: splitsmart-secrets
                  key: JWT_SECRET
            - name: GOOGLE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: splitsmart-secrets
                  key: GOOGLE_CLIENT_ID
            - name: GOOGLE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: splitsmart-secrets
                  key: GOOGLE_CLIENT_SECRET
            - name: GOOGLE_CALLBACK_URL
              valueFrom:
                secretKeyRef:
                  name: splitsmart-secrets
                  key: GOOGLE_CALLBACK_URL
            - name: GROQ_API_KEY
              valueFrom:
                secretKeyRef:
                  name: splitsmart-secrets
                  key: GROQ_API_KEY
            - name: CLIENT_URL
              valueFrom:
                secretKeyRef:
                  name: splitsmart-secrets
                  key: CLIENT_URL
---
apiVersion: v1
kind: Service
metadata:
  name: server
spec:
  selector:
    app: server
  ports:
    - port: 5000
      targetPort: 5000
